import { relations } from "drizzle-orm";
import { index, integer, pgTable, timestamp, text, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { adminUsers } from "../admin/admin-user";
import { timestamps } from "../timestamps";
import { waitlistAllocations } from "./waitlist-allocation";

/**
 * One round of invites sent against a release.
 *
 * ## Waves, not overbooking
 *
 * A wave is exactly as large as the release can fund: fifty invites for fifty
 * copies, then wait for the window to close and send the next wave from
 * whatever came back. The alternative is to overbook — invite seventy for
 * fifty on the assumption that some will not show — which is a legitimate
 * strategy and the wrong one here.
 *
 * Overbooking suits an airline, where the person bumped is a stranger
 * compensated at a published rate. The failure case here is a customer who was
 * texted that a copy was theirs, filled in a checkout form, and was told no —
 * and who will say so publicly, to an audience that overlaps almost entirely
 * with the shop's next hundred customers. The upside is a slightly faster
 * sell-through. It is not worth it, and this comment exists so the decision is
 * not quietly re-litigated by someone adding a fudge factor later.
 *
 * The cost of waves is latency: a copy whose holder ignores the SMS sits idle
 * for the whole window. That is what the TTL setting is for. A long queue is
 * an argument for a shorter window, not for overbooking.
 *
 * ## Why a table rather than the audit log
 *
 * The audit log already records who invited whom, as a JSON blob nothing can
 * join, aggregate or filter a list by. "Which wave is this person in, and has
 * it closed" is a question the panel asks on every render.
 */
export const waitlistInviteWaves = pgTable(
  "waitlist_invite_waves",
  {
    id: uuid("id").defaultRandom().primaryKey(),

    /* `restrict` for the same reason the entry's allocation reference is:
       deleting a release with waves against it would orphan the only record of
       how its copies were handed out. Releases are closed, never deleted. */
    allocationId: uuid("allocation_id")
      .notNull()
      .references(() => waitlistAllocations.id, { onDelete: "restrict" }),

    /** 1-based, per release. "Wave 2 of the September restock." */
    waveNumber: integer("wave_number").notNull(),

    /** How many entries got a link, and how many copies those links hold. The
     *  two differ whenever anyone asked for more than one copy. */
    invitedCount: integer("invited_count").notNull(),
    invitedQuantity: integer("invited_quantity").notNull(),

    /** The TTL in force when this wave went out, snapshotted — the shop-wide
     *  setting can move between waves, and "wave 1 had 48 hours" must stay
     *  true afterwards. */
    ttlHours: integer("ttl_hours").notNull(),

    /**
     * When this wave's last window shuts.
     *
     * A snapshot for the panel to render, never the authority: every check
     * that decides whether an invite can still be spent reads that entry's own
     * `invite_expires_at`. They are written from one value in one operation,
     * and this copy exists so "wave 2 closes in 6 hours" does not require
     * scanning entries.
     */
    closesAt: timestamp("closes_at", { withTimezone: true }).notNull(),

    sentById: uuid("sent_by_id").references(() => adminUsers.id, { onDelete: "set null" }),
    sentByEmail: text("sent_by_email"),

    ...timestamps,
  },
  (table) => [
    /* Two waves numbered 2 on the same release is a history that cannot be
       read back in order, and the number is generated by counting existing
       rows — so two admins sending at once would otherwise both write 2. */
    uniqueIndex("waitlist_invite_waves_allocation_number_idx").on(
      table.allocationId,
      table.waveNumber,
    ),

    index("waitlist_invite_waves_allocation_id_idx").on(table.allocationId),
  ],
);

export const waitlistInviteWavesRelations = relations(waitlistInviteWaves, ({ one }) => ({
  allocation: one(waitlistAllocations, {
    fields: [waitlistInviteWaves.allocationId],
    references: [waitlistAllocations.id],
  }),
}));
