import { Body, Controller, Headers, Post, Res } from "@nestjs/common";
import { ApiHeader, ApiOperation, ApiTags } from "@nestjs/swagger";
import { IDEMPOTENCY_KEY_HEADER, placeOrderRequestSchema, type Order } from "@sakura/contracts";
import type { Response } from "express";
import { createZodDto } from "nestjs-zod";
import { z } from "zod";
import { CheckoutService } from "./checkout.service";

class PlaceOrderDto extends createZodDto(placeOrderRequestSchema) {}

/**
 * A UUID, generated by the client when the checkout page mounts — not when the
 * button is pressed. Minting it on press would give a double-click two
 * different keys and defeat the entire mechanism.
 *
 * Validated as a schema rather than waved through, so the header is a checked
 * input like any other: `Idempotency-Key: 1` from a naive client would
 * otherwise become a permanent, globally-shared key that swallows every
 * subsequent order under it. A malformed header is the client's bug, so this
 * produces a 400 through the same VALIDATION_FAILED envelope as a bad body.
 */
const idempotencyKeySchema = z
  .string({ message: `Send an ${IDEMPOTENCY_KEY_HEADER} header, generated once per checkout.` })
  .uuid("The idempotency key must be a UUID generated by the client.");

@ApiTags("orders")
@Controller("orders")
export class OrdersController {
  constructor(private readonly checkoutService: CheckoutService) {}

  /**
   * Place an order.
   *
   * 201 when this request created it, 200 when it replayed an order the same
   * key already placed. Both return the identical body, which is the property
   * that matters: a client that lost the first response and retried gets its
   * order, and never a second one.
   *
   * Note the body has no total. The server re-prices everything from the
   * catalog inside the transaction, and there is nowhere for a client-supplied
   * amount to enter the calculation (§3.8).
   */
  @Post()
  @ApiOperation({ summary: "Place an order. Idempotent on the Idempotency-Key header." })
  @ApiHeader({
    name: IDEMPOTENCY_KEY_HEADER,
    required: true,
    description: "Client-generated UUID, stable across retries of one checkout.",
  })
  async place(
    @Body() body: PlaceOrderDto,
    @Headers(IDEMPOTENCY_KEY_HEADER) idempotencyKey: string | undefined,
    @Res({ passthrough: true }) response: Response,
  ): Promise<Order> {
    const key = idempotencyKeySchema.parse(idempotencyKey);
    const { order, created } = await this.checkoutService.placeOrder(body, key);

    // `passthrough` so Nest still serialises the return value; only the status
    // is taken over. Setting it here rather than with @HttpCode because the
    // code is a fact about what happened, not about the route.
    response.status(created ? 201 : 200);

    return order;
  }
}
