-- Make a reused payment receipt impossible, and make every gateway check
-- something the shop keeps rather than something it renders once.
--
-- ## Safety on an existing database
--
-- Every statement here is additive. No column is dropped, no value is
-- rewritten, and nothing existing changes meaning: `transaction_id` keeps
-- whatever the customer typed, and the new column is derived from it.
--
-- Orders placed before this migration are unaffected. A manual transfer from
-- 2024 whose receipt was never collected has NULL in the new column, which the
-- unique index ignores and the panel renders as "no receipt on file" — the
-- same thing it said before.
--
-- Two statements do take a heavy lock on `orders`: adding a stored generated
-- column rewrites the table, and CREATE UNIQUE INDEX blocks writes while it
-- builds. Both are seconds on a table of this size. Neither is written
-- CONCURRENTLY because that cannot run inside a transaction, and running this
-- file transactionally is worth more here than avoiding a brief lock: if the
-- duplicate check below fails, everything above it must roll back.
--
-- ## If this migration fails
--
-- It fails on purpose, in one case: existing orders already sharing a receipt.
-- Read the message, run `npm run db:receipt-duplicates` for the full list, and
-- resolve those orders — cancel the ones that were never really paid for, or
-- refund them. Then run this again. Nothing will have been applied.
--> statement-breakpoint

CREATE TYPE "public"."payment_verification_outcome" AS ENUM('MATCHED', 'UNDERPAID', 'NOT_FOUND', 'UNAVAILABLE');--> statement-breakpoint
ALTER TYPE "public"."audit_action" ADD VALUE 'DUPLICATE_RECEIPT_OVERRIDE';--> statement-breakpoint

-- Every cross-check, kept. Append-only: "not found at 09:12, found at 11:40"
-- is the actual story of a manual transfer, and one mutable column would keep
-- only the last frame of it.
CREATE TABLE "payment_verifications" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"order_id" uuid NOT NULL,
	"outcome" "payment_verification_outcome" NOT NULL,
	"transaction_id_normalised" text NOT NULL,
	"provider" "payment_provider",
	"paid_cents" integer,
	"expected_cents" integer,
	"received_at" timestamp with time zone,
	"reason" text,
	"checked_by_email" text,
	"raw" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "payment_verifications" ADD CONSTRAINT "payment_verifications_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "payment_verifications_order_idx" ON "payment_verifications" USING btree ("order_id","created_at" DESC NULLS LAST);--> statement-breakpoint

-- The form two receipts are compared in. Generated by Postgres so it cannot
-- drift from the TypeScript that used to compute it separately — those two
-- disagreed about non-breaking spaces, which is a receipt that never matched
-- itself and so was never caught as a duplicate.
ALTER TABLE "orders" ADD COLUMN "transaction_id_normalised" text GENERATED ALWAYS AS (nullif(upper(regexp_replace(coalesce("transaction_id", ''), '[^A-Za-z0-9]', '', 'g')), '')) STORED;--> statement-breakpoint

-- Refuse to add the constraint over data that already violates it.
--
-- Without this the next statement fails on its own, with Postgres naming one
-- arbitrary duplicate key and nothing else. That is a genuinely bad thing to
-- hit halfway through a release: the error does not say how many orders are
-- involved, which they are, or what to do. This says all three.
--
-- Note the normalisation is stricter than the old application-level check —
-- it now ignores hyphens and underscores too — so a pair like `PAY-123` and
-- `PAY123` may be reported here even though nothing flagged it before. That is
-- the check working, not a false positive.
DO $$
DECLARE
	duplicate_count integer;
	sample text;
BEGIN
	SELECT count(*), string_agg(orders_involved, '; ')
	INTO duplicate_count, sample
	FROM (
		SELECT string_agg(order_number, ', ' ORDER BY created_at) AS orders_involved
		FROM orders
		WHERE transaction_id_normalised IS NOT NULL
			AND status <> 'CANCELLED'
			AND status <> 'REFUNDED'
		GROUP BY transaction_id_normalised
		HAVING count(*) > 1
		LIMIT 10
	) AS duplicates;

	IF duplicate_count > 0 THEN
		RAISE EXCEPTION
			'% receipt(s) are shared by more than one live order, so the uniqueness index cannot be created. Orders involved: %. Cancel or refund the orders that were not really paid for, then run this migration again. Nothing has been applied.',
			duplicate_count, sample
			USING HINT = 'Run `npm run db:receipt-duplicates` in apps/api for the full list.';
	END IF;
END
$$;--> statement-breakpoint

-- One live order per receipt. The application check in
-- `findTransactionIdClaim` stays — it is what names the conflicting order in
-- an error message — but this is what makes the rule true, including for two
-- checkouts that read before either commits.
--
-- Partial on status because a cancelled or refunded order has let go of its
-- claim: the money was never taken or has been sent back, and the customer
-- re-placing that order with the same receipt is doing the right thing.
CREATE UNIQUE INDEX "orders_transaction_id_live_unique_idx" ON "orders" USING btree ("transaction_id_normalised") WHERE "status" <> 'CANCELLED' AND "status" <> 'REFUNDED';
