import { Body, Controller, Headers, Post, Res } from "@nestjs/common";
import { ApiHeader, ApiOperation, ApiTags } from "@nestjs/swagger";
import { IDEMPOTENCY_KEY_HEADER, placePreOrderRequestSchema, type PreOrder } from "@sakura/contracts";
import type { Response } from "express";
import { createZodDto } from "nestjs-zod";
import { z } from "zod";
import { StrictThrottle } from "../common/throttling/strict-throttle.decorator";
import { PreOrderCheckoutService } from "./pre-order-checkout.service";

class PlacePreOrderDto extends createZodDto(placePreOrderRequestSchema) {}

const idempotencyKeySchema = z
  .string({ message: `Send an ${IDEMPOTENCY_KEY_HEADER} header, generated once per pre-order.` })
  .uuid("The idempotency key must be a UUID generated by the client.");

/** Placing a pre-order. Mirrors OrdersController's shape (see checkout.service.ts's docs). */
@ApiTags("pre-orders")
@Controller("pre-orders")
export class PreOrdersController {
  constructor(private readonly preOrderCheckoutService: PreOrderCheckoutService) {}

  @Post()
  @StrictThrottle()
  @ApiOperation({ summary: "Place a pre-order. Idempotent on the Idempotency-Key header." })
  @ApiHeader({
    name: IDEMPOTENCY_KEY_HEADER,
    required: true,
    description: "Client-generated UUID, stable across retries of one submission.",
  })
  async place(
    @Body() body: PlacePreOrderDto,
    @Headers(IDEMPOTENCY_KEY_HEADER) idempotencyKey: string | undefined,
    @Res({ passthrough: true }) response: Response,
  ): Promise<PreOrder> {
    const key = idempotencyKeySchema.parse(idempotencyKey);
    const { preOrder, created } = await this.preOrderCheckoutService.placePreOrder(body, key);

    response.status(created ? 201 : 200);

    return preOrder;
  }
}
