import { createHash, createHmac } from "node:crypto";

/* --------------------------------------------------------------------------
   AWS Signature Version 4, enough of it to PUT and GET one object.

   Hand-written rather than `@aws-sdk/client-s3`, for the reason StorageService
   talks to storage over `fetch` in the first place: the whole of this app's
   relationship with the object store is "PUT these bytes" and "know the URL",
   and the SDK brings a hundred transitive packages, a credential-provider
   chain, a retry middleware stack and a region resolver to carry two requests
   that are a URL and five headers.

   The one thing that is genuinely not trivial — and the reason this file
   exists instead of a header on the fetch — is the signature itself, so it is
   isolated here and pinned by a test against a signature generated by
   botocore, the same signer the other app's backend uses against the same
   Garage cluster (test/unit/storage-sigv4.spec.ts).

   Scope, deliberately: unsigned payloads, chunked uploads, presigned URLs and
   session tokens are all absent. Add them when something needs them rather
   than writing a general signer nobody exercises.
   -------------------------------------------------------------------------- */

const ALGORITHM = "AWS4-HMAC-SHA256";
const SERVICE = "s3";

export type SignS3RequestInput = {
  method: "PUT" | "GET" | "HEAD" | "DELETE";
  /** Absolute URL, path already percent-encoded by `encodeObjectKey`. */
  url: string;
  region: string;
  accessKeyId: string;
  secretAccessKey: string;
  /** Headers to sign and send, names lowercase. `host`/`x-amz-*` are added here. */
  headers: Record<string, string>;
  /** Hex SHA-256 of the request body — `sha256Hex(body)`, or of "" for a GET. */
  payloadSha256: string;
  /** Injectable so the test can pin a timestamp; defaults to now. */
  now?: Date;
};

/** Hex SHA-256, the form both the canonical request and `x-amz-content-sha256` want. */
export function sha256Hex(payload: Uint8Array | string): string {
  return createHash("sha256").update(payload).digest("hex");
}

function hmac(key: Buffer | string, data: string): Buffer {
  return createHmac("sha256", key).update(data, "utf8").digest();
}

/**
 * Percent-encode an object key for use in a URL path.
 *
 * `/` stays a separator; everything outside RFC 3986's unreserved set is
 * escaped. `encodeURIComponent` leaves `!'()*` alone, which S3's canonical
 * URI rules do not, hence the second pass — it costs nothing and removes the
 * class of bug where a key signs one way and travels another.
 *
 * The signature is computed over this exact string and the request is sent to
 * this exact string, so the two cannot disagree even if a server would have
 * normalised them differently.
 */
export function encodeObjectKey(key: string): string {
  return key
    .split("/")
    .map((segment) =>
      encodeURIComponent(segment).replace(
        /[!'()*]/g,
        (character) => `%${character.charCodeAt(0).toString(16).toUpperCase()}`,
      ),
    )
    .join("/");
}

/** `20240101T000000Z` — the only timestamp format SigV4 accepts. */
function amzDate(now: Date): string {
  return `${now.toISOString().replace(/[-:]/g, "").split(".")[0]}Z`;
}

/**
 * Sign one request and return the headers to send with it.
 *
 * `host` is signed but deliberately *not* returned: `fetch` derives it from
 * the URL, which is the same value this signed, and passing it explicitly
 * risks a runtime setting it twice.
 */
export function signS3Request(input: SignS3RequestInput): Record<string, string> {
  const url = new URL(input.url);
  const now = input.now ?? new Date();
  const timestamp = amzDate(now);
  const dateStamp = timestamp.slice(0, 8);
  const scope = `${dateStamp}/${input.region}/${SERVICE}/aws4_request`;

  const signed: Record<string, string> = {};
  for (const [name, value] of Object.entries(input.headers)) {
    signed[name.toLowerCase()] = value;
  }
  signed.host = url.host;
  signed["x-amz-content-sha256"] = input.payloadSha256;
  signed["x-amz-date"] = timestamp;

  const names = Object.keys(signed).sort();
  /* Values are trimmed and their internal runs of whitespace collapsed, which
     is the spec's rule and not a tidy-up: a `cache-control` written with two
     spaces would otherwise sign as one thing and travel as another. */
  const canonicalHeaders = names
    .map((name) => `${name}:${signed[name].trim().replace(/\s+/g, " ")}\n`)
    .join("");
  const signedHeaders = names.join(";");

  const canonicalQuery = [...url.searchParams]
    .map(([key, value]) => [encodeObjectKey(key), encodeObjectKey(value)] as const)
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
    .map(([key, value]) => `${key}=${value}`)
    .join("&");

  const canonicalRequest = [
    input.method,
    url.pathname,
    canonicalQuery,
    canonicalHeaders,
    signedHeaders,
    input.payloadSha256,
  ].join("\n");

  const stringToSign = [ALGORITHM, timestamp, scope, sha256Hex(canonicalRequest)].join("\n");

  const signingKey = hmac(
    hmac(hmac(hmac(`AWS4${input.secretAccessKey}`, dateStamp), input.region), SERVICE),
    "aws4_request",
  );
  const signature = createHmac("sha256", signingKey).update(stringToSign, "utf8").digest("hex");

  /* `host` was signed but is not returned: `fetch` derives it from the URL,
     which is the same value, and setting it explicitly risks a runtime sending
     it twice. */
  const sendable = { ...signed };
  delete sendable.host;

  return {
    ...sendable,
    authorization:
      `${ALGORITHM} Credential=${input.accessKeyId}/${scope}, ` +
      `SignedHeaders=${signedHeaders}, Signature=${signature}`,
  };
}
