"use client";

import { useParams } from "next/navigation";
import { useEffect, useState, type FormEvent } from "react";
import type { AdminRole, AdminStaffMember } from "@sakura/contracts";

import { AdminTableRows } from "@/components/admin/skeletons";
import {
  Badge,
  Button,
  CopyButton,
  Input,
  Modal,
  Notice,
  Radio,
  RadioGroup,
} from "@/components/ui";
import {
  AdminApiError,
  createAdminStaff,
  listAdminStaff,
  resetAdminStaffPassword,
  setAdminStaffEnabled,
  updateAdminStaff,
} from "@/lib/api/admin";
import { ROLE_INFO, ROLE_ORDER } from "@/lib/admin-role-info";

/** Which dialog is open, and for whom. One at a time, by construction. */
type Dialog =
  | { kind: "add" }
  | { kind: "role"; member: AdminStaffMember }
  | { kind: "reset"; member: AdminStaffMember }
  | { kind: "disable"; member: AdminStaffMember }
  | { kind: "credential"; member: AdminStaffMember; password: string; reason: "created" | "reset" }
  | null;

/**
 * Settings → User Management.
 *
 * Who can sign in to the panel, and as what. The API holds every rule — no
 * changing your own role, never fewer than one active admin, sign-out
 * everywhere on a role change — so this page draws the obvious consequences
 * (greyed buttons on your own row) and otherwise shows the server's refusal
 * in its own words.
 *
 * Passwords are generated by the server and shown here once, in the
 * credential dialog, and nowhere else: not in the list, not in the audit log.
 */
export default function AdminUsersSettingsPage() {
  const [members, setMembers] = useState<AdminStaffMember[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [dialog, setDialog] = useState<Dialog>(null);

  useEffect(() => {
    let cancelled = false;

    listAdminStaff()
      .then((list) => {
        if (!cancelled) setMembers(list.items);
      })
      .catch((cause: unknown) => {
        if (!cancelled) setError(messageOf(cause, "Could not load staff accounts."));
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, []);

  /** Put a changed account back in its place in the list. */
  function replace(member: AdminStaffMember) {
    setMembers((prev) => {
      const exists = prev.some((item) => item.id === member.id);
      return exists
        ? prev.map((item) => (item.id === member.id ? member : item))
        : [...prev, member];
    });
  }

  const activeCount = members.filter((member) => !member.disabledAt).length;

  return (
    <div className="flex flex-col gap-10">
      <div className="flex flex-col gap-5">
        <div className="flex flex-wrap items-end justify-between gap-3">
          <p className="text-13.5 text-secondary max-w-xl">
            Everyone who can sign in to this panel, and what their role lets them do. Changing a
            role, resetting a password or disabling an account signs that person out everywhere,
            straight away.
          </p>
          <Button type="button" size="sm" onClick={() => setDialog({ kind: "add" })}>
            Add user
          </Button>
        </div>

        {error ? <Notice tone="error">{error}</Notice> : null}
        {notice ? <Notice>{notice}</Notice> : null}

        <div className="rounded-control border-rule bg-surface overflow-x-auto border">
          <table className="w-full min-w-180 text-left">
            <thead className="border-rule text-caption text-muted border-b">
              <tr>
                <th className="px-4 py-3 font-medium">Person</th>
                <th className="px-4 py-3 font-medium">Role</th>
                <th className="px-4 py-3 font-medium">Status</th>
                <th className="px-4 py-3 font-medium">Last sign-in</th>
                <th className="px-4 py-3" />
              </tr>
            </thead>
            <tbody className="text-13.5 divide-rule divide-y">
              {loading ? <AdminTableRows rows={3} columns={5} /> : null}

              {!loading
                ? members.map((member) => (
                    <StaffRow
                      key={member.id}
                      member={member}
                      onChangeRole={() => setDialog({ kind: "role", member })}
                      onReset={() => setDialog({ kind: "reset", member })}
                      onDisable={() => setDialog({ kind: "disable", member })}
                      onEnable={async () => {
                        setError(null);
                        setNotice(null);
                        try {
                          replace(await setAdminStaffEnabled(member.id, true));
                          setNotice(`${member.name} can sign in again.`);
                        } catch (cause) {
                          setError(messageOf(cause, "Could not re-enable that account."));
                        }
                      }}
                    />
                  ))
                : null}
            </tbody>
          </table>
        </div>

        {!loading ? (
          <p className="text-caption text-secondary">
            {activeCount} active account{activeCount === 1 ? "" : "s"}
            {members.length > activeCount ? ` · ${members.length - activeCount} disabled` : ""}
          </p>
        ) : null}
      </div>

      <RoleGuide />

      {dialog?.kind === "add" ? (
        <AddUserDialog
          onClose={() => setDialog(null)}
          onCreated={(member, password) => {
            replace(member);
            setNotice(null);
            setDialog({ kind: "credential", member, password, reason: "created" });
          }}
        />
      ) : null}

      {dialog?.kind === "role" ? (
        <ChangeRoleDialog
          member={dialog.member}
          onClose={() => setDialog(null)}
          onSaved={(member) => {
            replace(member);
            setDialog(null);
            setNotice(`${member.name} is now ${ROLE_INFO[member.role].label}.`);
          }}
        />
      ) : null}

      {dialog?.kind === "reset" ? (
        <ConfirmDialog
          title={`Reset ${dialog.member.name}'s password?`}
          body="Their current password stops working and they are signed out everywhere. You'll see the new one once, to hand over."
          confirmLabel="Reset password"
          onClose={() => setDialog(null)}
          onConfirm={async () => {
            const result = await resetAdminStaffPassword(dialog.member.id);
            replace(result.user);
            setNotice(null);
            setDialog({
              kind: "credential",
              member: result.user,
              password: result.temporaryPassword,
              reason: "reset",
            });
          }}
        />
      ) : null}

      {dialog?.kind === "disable" ? (
        <ConfirmDialog
          title={`Disable ${dialog.member.name}?`}
          body="They are signed out everywhere and can't sign in until you re-enable the account. Nothing they did is deleted — their history stays in the audit log."
          confirmLabel="Disable account"
          destructive
          onClose={() => setDialog(null)}
          onConfirm={async () => {
            const updated = await setAdminStaffEnabled(dialog.member.id, false);
            replace(updated);
            setDialog(null);
            setNotice(`${updated.name} can no longer sign in.`);
          }}
        />
      ) : null}

      {dialog?.kind === "credential" ? (
        <CredentialDialog
          member={dialog.member}
          password={dialog.password}
          reason={dialog.reason}
          onClose={() => setDialog(null)}
        />
      ) : null}
    </div>
  );
}

function StaffRow({
  member,
  onChangeRole,
  onReset,
  onDisable,
  onEnable,
}: {
  member: AdminStaffMember;
  onChangeRole: () => void;
  onReset: () => void;
  onDisable: () => void;
  onEnable: () => Promise<void>;
}) {
  const [enabling, setEnabling] = useState(false);
  const disabled = member.disabledAt !== null;
  // The server refuses these for your own account; the row says so up front.
  const selfHint = member.isSelf ? "Ask another admin to change your own account." : undefined;

  return (
    <tr className={disabled ? "opacity-60" : undefined}>
      <td className="px-4 py-3">
        <span className="text-ink flex items-center gap-2 font-medium">
          {member.name}
          {member.isSelf ? <Badge>You</Badge> : null}
        </span>
        <span className="text-secondary block">{member.email}</span>
      </td>
      <td className="px-4 py-3">
        <Badge tone={member.role === "ADMIN" ? "outline" : "neutral"}>
          {ROLE_INFO[member.role].label}
        </Badge>
      </td>
      <td className="text-secondary px-4 py-3">{disabled ? "Disabled" : "Active"}</td>
      <td className="text-secondary px-4 py-3">
        {member.lastLoginAt ? new Date(member.lastLoginAt).toLocaleString() : "Never"}
      </td>
      <td className="px-4 py-3">
        <div className="flex flex-wrap justify-end gap-2">
          {disabled ? (
            <Button
              type="button"
              size="sm"
              variant="secondary"
              loading={enabling}
              onClick={() => {
                setEnabling(true);
                void onEnable().finally(() => setEnabling(false));
              }}
            >
              Re-enable
            </Button>
          ) : (
            <>
              <Button
                type="button"
                size="sm"
                variant="secondary"
                disabled={member.isSelf}
                title={selfHint}
                onClick={onChangeRole}
              >
                Change role
              </Button>
              <Button
                type="button"
                size="sm"
                variant="ghost"
                disabled={member.isSelf}
                title={selfHint}
                onClick={onReset}
              >
                Reset password
              </Button>
              <Button
                type="button"
                size="sm"
                variant="destructive"
                disabled={member.isSelf}
                title={selfHint}
                onClick={onDisable}
              >
                Disable
              </Button>
            </>
          )}
        </div>
      </td>
    </tr>
  );
}

/** The three roles as radios, each with the one line that tells them apart. */
function RolePicker({
  value,
  onChange,
}: {
  value: AdminRole;
  onChange: (role: AdminRole) => void;
}) {
  return (
    <RadioGroup name="role" label="Role">
      {ROLE_ORDER.map((role) => (
        <Radio
          key={role}
          value={role}
          checked={value === role}
          onChange={() => onChange(role)}
          description={ROLE_INFO[role].summary}
        >
          {ROLE_INFO[role].label}
        </Radio>
      ))}
    </RadioGroup>
  );
}

function AddUserDialog({
  onClose,
  onCreated,
}: {
  onClose: () => void;
  onCreated: (member: AdminStaffMember, password: string) => void;
}) {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  // The narrowest role by default: widening access should be a choice, not
  // the result of not reading the form.
  const [role, setRole] = useState<AdminRole>("FULFILLMENT");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function submit(event: FormEvent) {
    event.preventDefault();
    setBusy(true);
    setError(null);

    try {
      const result = await createAdminStaff({ name, email, role });
      onCreated(result.user, result.temporaryPassword);
    } catch (cause) {
      setError(messageOf(cause, "Could not add that account."));
      setBusy(false);
    }
  }

  return (
    <Modal
      open
      size="md"
      onClose={onClose}
      title="Add user"
      description="They'll get a temporary password, shown to you once on the next screen."
    >
      <form onSubmit={(event) => void submit(event)} className="flex flex-col gap-5">
        <Input
          label="Name"
          value={name}
          onChange={(event) => setName(event.target.value)}
          autoComplete="off"
          required
        />
        <Input
          label="Email"
          hint="What they sign in with."
          type="email"
          value={email}
          onChange={(event) => setEmail(event.target.value)}
          autoComplete="off"
          required
        />
        <RolePicker value={role} onChange={setRole} />

        {error ? <Notice tone="error">{error}</Notice> : null}

        <div className="flex flex-wrap gap-2">
          <Button type="submit" loading={busy}>
            Add user
          </Button>
          <Button type="button" variant="ghost" disabled={busy} onClick={onClose}>
            Cancel
          </Button>
        </div>
      </form>
    </Modal>
  );
}

function ChangeRoleDialog({
  member,
  onClose,
  onSaved,
}: {
  member: AdminStaffMember;
  onClose: () => void;
  onSaved: (member: AdminStaffMember) => void;
}) {
  const [role, setRole] = useState<AdminRole>(member.role);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function save() {
    setBusy(true);
    setError(null);

    try {
      onSaved(await updateAdminStaff(member.id, { role }));
    } catch (cause) {
      setError(messageOf(cause, "Could not change that role."));
      setBusy(false);
    }
  }

  return (
    <Modal
      open
      size="md"
      onClose={onClose}
      title={`Change ${member.name}'s role`}
      description="They'll be signed out and see their new access when they sign in again."
      actions={
        <>
          <Button
            type="button"
            loading={busy}
            disabled={role === member.role}
            onClick={() => void save()}
          >
            Save role
          </Button>
          <Button type="button" variant="ghost" disabled={busy} onClick={onClose}>
            Cancel
          </Button>
        </>
      }
    >
      <div className="flex flex-col gap-4">
        <RolePicker value={role} onChange={setRole} />
        {error ? <Notice tone="error">{error}</Notice> : null}
      </div>
    </Modal>
  );
}

function ConfirmDialog({
  title,
  body,
  confirmLabel,
  destructive,
  onClose,
  onConfirm,
}: {
  title: string;
  body: string;
  confirmLabel: string;
  destructive?: boolean;
  onClose: () => void;
  onConfirm: () => Promise<void>;
}) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function confirm() {
    setBusy(true);
    setError(null);

    try {
      await onConfirm();
    } catch (cause) {
      setError(messageOf(cause, "That didn't go through."));
      setBusy(false);
    }
  }

  return (
    <Modal
      open
      onClose={onClose}
      title={title}
      description={body}
      actions={
        <>
          <Button
            type="button"
            variant={destructive ? "destructive" : "primary"}
            loading={busy}
            onClick={() => void confirm()}
          >
            {confirmLabel}
          </Button>
          <Button type="button" variant="ghost" disabled={busy} onClick={onClose}>
            Cancel
          </Button>
        </>
      }
    >
      {error ? <Notice tone="error">{error}</Notice> : null}
    </Modal>
  );
}

/**
 * The one screen that ever shows a password.
 *
 * Everything the owner needs to hand over is on it — where to sign in, the
 * email, the password — so it can be read out or copied in one go, and it
 * says plainly that closing it is the end of the password's visibility.
 */
function CredentialDialog({
  member,
  password,
  reason,
  onClose,
}: {
  member: AdminStaffMember;
  password: string;
  reason: "created" | "reset";
  onClose: () => void;
}) {
  const { locale } = useParams<{ locale: string }>();
  const loginUrl = `${window.location.origin}/${locale}/admin/login`;
  const handover = `Sign in at ${loginUrl}\nEmail: ${member.email}\nPassword: ${password}`;

  return (
    <Modal
      open
      size="md"
      onClose={onClose}
      title={reason === "created" ? `${member.name} can now sign in` : "New password set"}
      description={`Role: ${ROLE_INFO[member.role].label}. Give them these details in person or over a private message.`}
      actions={
        <Button type="button" onClick={onClose}>
          Done
        </Button>
      }
    >
      <div className="flex flex-col gap-4">
        <dl className="text-13.5 border-rule flex flex-col gap-2 rounded-md border p-4">
          <HandoverRow label="Sign in at" value={loginUrl} />
          <HandoverRow label="Email" value={member.email} />
          <HandoverRow label="Password" value={password} mono />
        </dl>

        <div className="flex items-center gap-2">
          <CopyButton value={handover} />
          <span className="text-caption text-secondary">Copy all three</span>
        </div>

        <Notice lead="Shown once.">
          After you close this, nobody can see this password again. If it is lost, reset it.
        </Notice>
      </div>
    </Modal>
  );
}

function HandoverRow({ label, value, mono }: { label: string; value: string; mono?: boolean }) {
  return (
    <div className="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-1">
      <dt className="text-muted">{label}</dt>
      <dd className={`text-ink break-all ${mono ? "font-mono" : ""}`}>{value}</dd>
    </div>
  );
}

/** What each role can and cannot do, so the choice is made with the facts. */
function RoleGuide() {
  return (
    <div className="flex flex-col gap-4">
      <div>
        <h2 className="text-h4 text-ink font-serif">What each role can do</h2>
        <p className="text-13.5 text-secondary mt-1">
          Give each person the narrowest role that covers their work.
        </p>
      </div>

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-3">
        {ROLE_ORDER.map((role) => {
          const info = ROLE_INFO[role];

          return (
            <section
              key={role}
              className="rounded-container border-rule bg-surface p-card flex flex-col gap-3 border"
            >
              <div>
                <h3 className="text-ink font-medium">{info.label}</h3>
                <p className="text-13.5 text-secondary mt-1">{info.summary}</p>
              </div>

              <RoleList heading="Can" items={info.can} />
              <RoleList heading="Can't" items={info.cannot} />
            </section>
          );
        })}
      </div>
    </div>
  );
}

function RoleList({ heading, items }: { heading: string; items: readonly string[] }) {
  return (
    <div>
      <p className="text-caption text-muted mb-1">{heading}</p>
      <ul className="text-13.5 text-secondary flex list-disc flex-col gap-1 pl-4">
        {items.map((item) => (
          <li key={item}>{item}</li>
        ))}
      </ul>
    </div>
  );
}

function messageOf(cause: unknown, fallback: string): string {
  return cause instanceof AdminApiError ? cause.message : fallback;
}
